### PR TITLE
Logo changed

### LINKED ISSUE #24: Change logo
_IDS logooos
Shu logoni qo'yinglar.

### PR DESCRIPTION
**Pull request by zeeztasium**
Logo'ni o'zgartirdim @wahid-d 

closes #24

### CODE REVIEW

**Comment by wahidustoz** [comment]
@MrAziz-bek Attach screenshot.

**Comment by zeeztasium** [comment]
@wahid-d logo ni o'zgartirdim svg ga, + footer ham bor

**Comment by wahidustoz** [comment]
@MrAziz-bek Screenshot ko'rsating dedimku

**Comment by zeeztasium** [comment]
Screen Shot 2022-02-03 at 10 36 45

**Comment by zeeztasium** [comment]
@wahid-d ⬆️

**Pull request merged**
